### ISSUE TITLE
projection matrix for 3d cone geometry

### ISSUE THREAD

**Issue by listar0810** [ahendriksen/tomosipo#19]
how to get the projection matrix of 3D (cone) 
Can a sample code be added to obtain the Projection matrix for 3d cone geometry!

Thanks

**Comment by ahendriksen** [comment]
Can't you just loop over the voxels, put in a single 1, and project? Then you get the rows of the matrix.

**Comment by D1rk123** [comment]
There is no function for obtaining the projection matrix directly. The projection matrix is never fully stored in memory because it would take up a huge amount of memory (and most of that memory would be filled with zeros). Instead it is calculated on the fly. if you have an NxNxN volume, an NxN detector and N projections the result is a matrix with N^6 values (of 4 bytes each for 32bit floats). Already for N=128 you would need (128^6*4)/(1024^3)=16384Gb of memory to store it.

For very small geometries (ie. N=32) you can still store the matrix in memory. I've written a small function to calculate the matrix:
```
import numpy as np
import torch
import tomosipo as ts

def operator_to_matrix(op):
    domain_size = np.prod(op.domain_shape)
    range_size = np.prod(op.range_shape)
    device = torch.device("cuda:0")
    result = torch.zeros(range_size, domain_size, dtype=torch.float32, device=device)
    one_voxel = torch.zeros(domain_size, dtype=torch.float32, device=device)
    one_voxel_view = one_voxel.view(op.domain_shape)
    
    print(result.shape)
    
    for i in tqdm(range(domain_size)):
        for j in range(range_size):
            one_voxel[i] = 1
            result[:, i] = op(one_voxel_view).flatten()
            one_voxel[i] = 0
            
    return result.cpu().numpy()
```

Admittedly this code is quite inefficient because it calculates a whole projection for every row in the matrix that you want to look up. A faster implementation would require a change in Astra (the core library Tomosipo is based on). You could try doing a feature request there.

**Comment by listar0810** [comment]
@D1rk123 thanks a lot , really helps. and thx @ahendriksen. I will close it.

**Comment by listar0810** [comment]
@D1rk123 Thanks again for the modification.
