### ISSUE TITLE
Silent corruption when GPU array is not aligned to 128 bytes

### ISSUE THREAD

**Issue by ahendriksen** [ahendriksen/tomosipo#6]
See astra-toolbox issue: https://github.com/astra-toolbox/astra-toolbox/issues/280#issuecomment-805838534

To reproduce: 
``` python
import torch 
import tomosipo as ts
vg = ts.volume(shape=(32, 32, 32), size=(1, 1, 1))
pg = ts.parallel(angles=32, shape=(35, 35), size=(1.5, 1.5))
A = ts.operator(vg, pg)
x = torch.ones(A.domain_shape).cuda()
y = A(x)
```

There are artifacts in y, because the data is not strided by 128 bytes.

**Comment by wjp** [comment]
This should now be fixed in astra by astra-toolbox/astra-toolbox@e99c6a75bada269381b247c555786dda8b390b7a . Also astra-toolbox/astra-toolbox@d17f6102ab60863b3dead22d619a313aa277e514 adds a feature flag `unpadded_GPULink` should you want to detect if astra is new enough to properly handle this (with `astra.has_feature('unpadded_GPULink')`).

**Comment by D1rk123** [comment]
I ran the script posted by ahendriksen on the current version of Tomosipo, and I noticed no artifacts, so this issue is indeed fixed
